print(5+5)
print(5-5)
print(5*5)
print(5/5)
print(5%5)
print(5**5)
print(5//5)
print("José Luis Rangel Zayas")
print("La familia Rangel Zayas")
print("México")
print("Ia am enjoying 30 days of Phyton")

print(type(10))
print(type(9.8))
print(type(3.14))
print(type(4-4j))
print(type('Asabeneh','Phyton','Finland'))
print(type("José Luis Rangel Zayas"))
print(type("Rangel Zayas"))
print(type("México"))


